default_root_dir: experiments/sweep
sweep_configuration:
  method: grid
  metric:
    name: val_acc
    goal: maximize
  parameters:
    model:
      type:
        sweep: True
        sweep_alias: [type1, type2]
        values: [resnet, densenet]
    data:
      chiz:
        sweep: True
        sweep_alias: [chiz1, chiz2]
        values:
          - sweep_list_operations:
              - sweep_overwrite: [0, 10]
          - sweep_list_operations:
              - sweep_overwrite: [1, 11]
    upsert:
      - optimizer:
          type:
            dy_eval:
              expression: |
                def func(config):
                  return config['model']['type'] == 'resnet'
              function_of_interest: func

base_config:
  data:
    dataset: cifar10
    batch_size: 128
    chiz: [1, 2, 3]
  model:
    type: resnet
    depth: 20
  optimizer:
    type: sgd
    lr: 0.1
#
project: hierarchical_sweep
count: 1
resume: False
run_name: hamid
checkpoint_interval: 3600
#
use_lightning_logger: False
