data:
  dataset_class: torchvision.datasets.CIFAR10
  batch_size: 64
  num_workers: 2
  train_transforms:
  - class_path: torchvision.transforms.RandomHorizontalFlip
  - class_path: torchvision.transforms.RandomCrop
    init_args:
        size: 32
        padding: 4
  - class_path: torchvision.transforms.ToTensor
  - class_path: torchvision.transforms.Normalize
    init_args:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  test_transforms:
  - class_path: torchvision.transforms.ToTensor
  - class_path: torchvision.transforms.Normalize
    init_args:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
model:
  class_path: torchvision.models.resnet50
  init_args:
    pretrained: False
    num_classes: 10
trainer:
  epoch_count: 10
  optimizer:
    class_path: torch.optim.SGD
    init_args:
      lr: 0.001